### ISSUE TITLE
TEST: Create test for redirect() method

### ISSUE THREAD

**Issue by Soviut** [ecoal95/php-router#9]
Sadly, I'm way less familiar with testing in PHP than other languages so I'm not fit to implement this at the moment.

**Comment by emilio** [comment]
Yep, PHP testing sucks because there's so much global state (`header`, `http_response_code`, ...).

I was able to test this using xdebug in the last commits (mainly https://github.com/ecoal95/php-router/commit/28c5ff5ec18db2d85be8b59ebe4fef4e0f31b811), so I'll close this.

Note that in order to test this I had to remove the `exit` statement from the `redirect` method, but I don't expect this to be a problem :P
